### ISSUE TITLE
Adding GitLens

### ISSUE THREAD

**Issue by ruipacheco** [Zerotask/vscode-rust-pack#2]
Would you be open to me adding GitLens to the list of plugins? I find it very useful.

**Comment by Zerotask** [comment]
Thank you for your request.

I really like this extension and I'm using it for a long time now, but I want to focus this extension pack on directly with Rust related extensions.
I just want to cover:
- writing
- testing
- debugging

and I don't want to bloat it up with other (useful) extensions which don't fit here.

GitLens is more of a productivity extension and not needed to develop and maintain Rust applications.
