### ISSUE TITLE
Rust Analyzer is not installing

### ISSUE THREAD

**Issue by salvadormarcos** [Zerotask/vscode-rust-pack#8]
Hello,

I just installed this Extension Pack and noticed that Rust Analyzer is not installing automatically.

Apparently Rust Analyzer's Extension ID changed from "matklad.rust-analyzer" to "rust-lang.rust-analyzer"

**Comment by Zerotask** [comment]
Hey @salvadormarcos 

Thank you for your bug report. I just [fixed it ](https://github.com/Zerotask/vscode-rust-extension-pack/commit/f652d3aa599f012475d47374ed63239a70ebb3f9)and released Version 1.1.1
